//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.0.2+497c31e
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Контентная страница</summary>
	[PublishedModel("contentPage")]
	public partial class ContentPage : PublishedContentModel, INavigationSettings, IRoutingSettings, ISysSeoPage
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const string ModelTypeAlias = "contentPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<ContentPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ContentPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// @Conctructor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("conctructor")]
		public virtual long Conctructor => this.Value<long>(_publishedValueFallback, "conctructor");

		///<summary>
		/// Не показывать узел в хлебных крошках
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("hideInBreadCrambs")]
		public virtual bool HideInBreadCrambs => global::Umbraco.Cms.Web.Common.PublishedModels.NavigationSettings.GetHideInBreadCrambs(this, _publishedValueFallback);

		///<summary>
		/// Показывать вложенные страницы: Для отображения в многоуровневых меню
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("isShowChildrens")]
		public virtual bool IsShowChildrens => global::Umbraco.Cms.Web.Common.PublishedModels.NavigationSettings.GetIsShowChildrens(this, _publishedValueFallback);

		///<summary>
		/// Скрыть узел без распубликации
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Umbraco.Cms.Web.Common.PublishedModels.NavigationSettings.GetUmbracoNaviHide(this, _publishedValueFallback);

		///<summary>
		/// umbracoInternalRedirectId: Umbraco загрузит содержимое выбранной страницы незаметно, без перенаправления URL-адресов. По сути, это приводит к переписыванию кода.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoInternalRedirectId => global::Umbraco.Cms.Web.Common.PublishedModels.RoutingSettings.GetUmbracoInternalRedirectId(this, _publishedValueFallback);

		///<summary>
		/// Редирект на другую страницу сайта
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoRedirect")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoRedirect => global::Umbraco.Cms.Web.Common.PublishedModels.RoutingSettings.GetUmbracoRedirect(this, _publishedValueFallback);

		///<summary>
		/// Красивый адрес для страницы: Укажите красивое и понятное имя страницы для отображения в адресной строке - без '/' или '\'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlName")]
		public virtual string UmbracoUrlName => global::Umbraco.Cms.Web.Common.PublishedModels.RoutingSettings.GetUmbracoUrlName(this, _publishedValueFallback);

		///<summary>
		/// Не показывать страницу в карте сайта
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetHideFromSitemap(this, _publishedValueFallback);

		///<summary>
		/// Описание
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Ключевые слова
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaKeywords")]
		public virtual string MetaKeywords => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetMetaKeywords(this, _publishedValueFallback);

		///<summary>
		/// Заголовок страницы
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaTitle")]
		public virtual string MetaTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetMetaTitle(this, _publishedValueFallback);
	}
}
