//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.0.2+497c31e
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("indexPage")]
	public partial class IndexPage : PublishedContentModel, ISysSeoPage, ITopLevelNode
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const string ModelTypeAlias = "indexPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<IndexPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public IndexPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// @Constructor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("constructor")]
		public virtual string Constructor => this.Value<string>(_publishedValueFallback, "constructor");

		///<summary>
		/// Не показывать страницу в карте сайта
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetHideFromSitemap(this, _publishedValueFallback);

		///<summary>
		/// Описание
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Ключевые слова
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaKeywords")]
		public virtual string MetaKeywords => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetMetaKeywords(this, _publishedValueFallback);

		///<summary>
		/// Заголовок страницы
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaTitle")]
		public virtual string MetaTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SysSeoPage.GetMetaTitle(this, _publishedValueFallback);

		///<summary>
		/// Иконка для IOS: PNG в размере 180x180
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("faviconIOS")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FaviconIos => global::Umbraco.Cms.Web.Common.PublishedModels.TopLevelNode.GetFaviconIos(this, _publishedValueFallback);

		///<summary>
		/// Фавикон: Файл в формате SVG - favicon.svg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("faviconNB")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FaviconNB => global::Umbraco.Cms.Web.Common.PublishedModels.TopLevelNode.GetFaviconNB(this, _publishedValueFallback);

		///<summary>
		/// Footer Constructor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("footerConstructor")]
		public virtual int FooterConstructor => global::Umbraco.Cms.Web.Common.PublishedModels.TopLevelNode.GetFooterConstructor(this, _publishedValueFallback);

		///<summary>
		/// Конструкитор шапки для десктопа
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerConstructor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel HeaderConstructor => global::Umbraco.Cms.Web.Common.PublishedModels.TopLevelNode.GetHeaderConstructor(this, _publishedValueFallback);

		///<summary>
		/// Headr Constructor for Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headrConstructorForMobile")]
		public virtual string HeadrConstructorForMobile => global::Umbraco.Cms.Web.Common.PublishedModels.TopLevelNode.GetHeadrConstructorForMobile(this, _publishedValueFallback);

		///<summary>
		/// Счетчики и дополниельные META в head
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaExtended")]
		public virtual string MetaExtended => global::Umbraco.Cms.Web.Common.PublishedModels.TopLevelNode.GetMetaExtended(this, _publishedValueFallback);

		///<summary>
		/// Изображение  по умолчанию: Используется как заглушка если нет контентного
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rootDefaultImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RootDefaultImage => global::Umbraco.Cms.Web.Common.PublishedModels.TopLevelNode.GetRootDefaultImage(this, _publishedValueFallback);
	}
}
