//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.0.2+497c31e
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "topLevelNode"
	/// <summary>Top-level Node</summary>
	public partial interface ITopLevelNode : IPublishedElement
	{
		/// <summary>Иконка для IOS</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops FaviconIos { get; }

		/// <summary>Фавикон</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops FaviconNB { get; }

		/// <summary>Footer Constructor</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		int FooterConstructor { get; }

		/// <summary>Конструкитор шапки для десктопа</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel HeaderConstructor { get; }

		/// <summary>Headr Constructor for Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HeadrConstructorForMobile { get; }

		/// <summary>Счетчики и дополниельные META в head</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string MetaExtended { get; }

		/// <summary>Изображение  по умолчанию</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops RootDefaultImage { get; }
	}

	/// <summary>Top-level Node</summary>
	[PublishedModel("topLevelNode")]
	public partial class TopLevelNode : PublishedElementModel, ITopLevelNode
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const string ModelTypeAlias = "topLevelNode";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<TopLevelNode, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public TopLevelNode(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Иконка для IOS: PNG в размере 180x180
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("faviconIOS")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FaviconIos => GetFaviconIos(this, _publishedValueFallback);

		/// <summary>Static getter for Иконка для IOS</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetFaviconIos(ITopLevelNode that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "faviconIOS");

		///<summary>
		/// Фавикон: Файл в формате SVG - favicon.svg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("faviconNB")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FaviconNB => GetFaviconNB(this, _publishedValueFallback);

		/// <summary>Static getter for Фавикон</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetFaviconNB(ITopLevelNode that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "faviconNB");

		///<summary>
		/// Footer Constructor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[ImplementPropertyType("footerConstructor")]
		public virtual int FooterConstructor => GetFooterConstructor(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Constructor</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		public static int GetFooterConstructor(ITopLevelNode that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "footerConstructor");

		///<summary>
		/// Конструкитор шапки для десктопа
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerConstructor")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel HeaderConstructor => GetHeaderConstructor(this, _publishedValueFallback);

		/// <summary>Static getter for Конструкитор шапки для десктопа</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel GetHeaderConstructor(ITopLevelNode that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel>(publishedValueFallback, "headerConstructor");

		///<summary>
		/// Headr Constructor for Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headrConstructorForMobile")]
		public virtual string HeadrConstructorForMobile => GetHeadrConstructorForMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Headr Constructor for Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHeadrConstructorForMobile(ITopLevelNode that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "headrConstructorForMobile");

		///<summary>
		/// Счетчики и дополниельные META в head
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaExtended")]
		public virtual string MetaExtended => GetMetaExtended(this, _publishedValueFallback);

		/// <summary>Static getter for Счетчики и дополниельные META в head</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetMetaExtended(ITopLevelNode that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "metaExtended");

		///<summary>
		/// Изображение  по умолчанию: Используется как заглушка если нет контентного
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rootDefaultImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RootDefaultImage => GetRootDefaultImage(this, _publishedValueFallback);

		/// <summary>Static getter for Изображение  по умолчанию</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.0.2+497c31e")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetRootDefaultImage(ITopLevelNode that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "rootDefaultImage");
	}
}
